networks:
    lms-network:
        driver: bridge
        external: false

include:
    -   kafka/docker-compose.yml
    -   nginx/docker-compose.yml
    -   oauth2-proxy/docker-compose.yml
    -   postgres/docker-compose.yml
    -   dexIdP/docker-compose.yml


services:
    students-service:
        image: ayozav-students-service:0.1.0
        build:
            context: ./students-service
        container_name: LMS.StudentsService

        develop:
            watch:
                # LMS собирается в jar'ник...
                -   path: ./students-service/src/
                    action: rebuild
        restart: no

        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 512M

        depends_on:
            postgres:
                condition: service_healthy
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
            kafka3:
                condition: service_healthy

        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider",
                "http://localhost:4040/echo"]
            interval: 5s
            timeout: 5s
            retries: 5

        env_file:
            - .env

        networks:
            - lms-network
