volumes:
    postgres_data:
        # Создаём том для данных Postgres.


services:
    # Он нам нужен для хранения вообще всей информации по LMS!
    # Бизнесовая часть в том числе.
    postgres:
        image: postgres:18
        container_name: "LMS.Postgres"
        restart: no

        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            DATABASE_SCHEMA: ${DATABASE_SCHEMA}
            DATABASE_NAME: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${DATABASE_PORT}:5432"

        # Для прод. версии следует убрать!
        command: ["postgres", "-c", "log_statement=all"]

        volumes:
            # - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
            - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro   # Запуск собственных инит. скрипта.
            - postgres_data:/var/lib/postgresql  # Определяем, где будет лежать вся СУБД

        # Задаём чёткий скрипт, который позволяет нам убедится, что сервис живой.
        healthcheck:
            # Внутри мы указываем порт в Докере.
            # А товарищ Postgres по умолчанию на порту 5432 живёт.
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
            interval: 3s
            retries: 5
            start_period: 15s
            timeout: 5s

        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 512M

    # Он нам нужен, чтобы красиво и грамотно агрегировать все запросы
    # извне вовнутрь (с переходом в Докер, соответственно).
    nginx:
        image: nginx:1.29.8
        container_name: "LMS.Nginx"
        volumes:
            # Явно указываем, что настройки лежат в проектной папке
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            # Пробрасываем 80 порт в контейнер.
            - "80:80"
        # Прежде чем поднять Nginx - все сервисы должны подняться.
        # Тогда пользователи гарантированно получат рабочие ответы!
        depends_on:
            postgres:
                condition: service_healthy

        # Во время домашней разработке, мы вынуждены пробрасывать своё решение на основную машину.
        # Чтобы Джавалин мог ловить происходящее.
        extra_hosts:
            - "host.docker.internal:host-gateway"   # позволяет резолвить имя хоста

        # Жёстко-жёстко ограничиваем (мы бедные студенты,
        # у нас кремний не такой крутой, как на больших серверах)
        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 512M
        restart: no

    lms:
        build:
            context: ./students-service

        container_name: "LMS"
        ports:
            - "4040:4040"

        env_file:
            -   .env
