services:
    logto:
        container_name: "LMS.LogTo"
        depends_on:
            postgres:
                condition: service_healthy
        image: svhd/logto:latest
        entrypoint: [ "sh", "-c", "npm run cli db seed -- --swe && npm start" ]
        ports:
            - "3001:3001"  # Порт для входа (доступен извне)
            - "3002:3002"  # Админка (доступен извне)

        environment:
            TRUST_PROXY_HEADER: 1

        env_file:
            -   .env

        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 512M

        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/status"]
            interval: 10s
            timeout: 5s
            retries: 5
