events {}

http {
    # Эта строка подключает глобальный файл с MIME-типами
    include /etc/nginx/mime.types;
    # Строка ниже задаёт тип по умолчанию. Без неё иногда возникают ошибки
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            proxy_pass http://students-service:4040/;
        }

        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }

    }
}